server:
  port: 8010
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/profileapp?encoding=UTF-8
    username: profileapp
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
api-key: secret
